[package]
name = "project1-echo-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared = { path = "../shared" }
anyhow.workspace = true
thiserror.workspace = true
clap.workspace = true

[dev-dependencies]

