[package]
name = "project5-event-scheduler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared = { path = "../shared" }
tokio.workspace = true
anyhow.workspace = true

[dev-dependencies]
tokio-test = "0.4"

